In [2]:
import numpy as np
print(np.__version__)

1.22.4


# Creating an array


In [7]:
a = [10, 20, 30, 40, 50]
print(a)
type(a)
b = np.array(a)
print(b)
print(type(b))

[10, 20, 30, 40, 50]
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [8]:
b + 100

array([110, 120, 130, 140, 150])

In [12]:
# shape
b.shape
b.dtype

dtype('int32')

In [16]:
a = np.array([1, 2, 3, 4, 5, 6, 6, 10], ndmin=2, dtype=float)
print(a)
a.shape

[[ 1.  2.  3.  4.  5.  6.  6. 10.]]


(1, 8)

In [20]:
# two dimension
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.shape)


(2, 3)
